project:
  type: website
  output-dir: docs # command to allow publishing using docs (https://quarto.org/docs/publishing/github-pages.html)

website:

  title: "Biologia della Conservazione 24/25"
  reader-mode: true
  page-navigation: true
  description: ""
  site-url: https://giulianocolosimo.github.com
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [issue]
  open-graph:
    locale: en_US
  
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Calendar"
        href: calendar.qmd
      - text: "Contact"
        href: contact.qmd

  sidebar:
    logo: "./figures/avatar.jpg"
    pinned: false
    align: center
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - section: "Classes"
        title: "Classes"
        contents: 
          - href: ./classes/1/class_1.html
            text: "Class 1 - Introduction to Conservation Biology"
          - href: ./classes/2/class_2.html
            text: "Class 2 - Biodiversity"
          - href: ./classes/3/class_3.html
            text: "Class 3 - Anthropocene"
          - href: ./classes/4/class_4.html
            text: "Class 4 - Populations and conservation genetics"
          - href: ./classes/5/class_5.html
            text: "Class 5 - HW and Genetic drift"
          - href: ./classes/6/class_6.html
            text: "Class 6 - $N_{e}$ and Population structure"
          - href: ./classes/7/class_7.html
            text: "Class 7 - Inbreeding and Inbreeding depression"
          - href: ./classes/8/class_8.html
            text: "Class 8 - Hybridization and heritability"


    tools:
      - icon: envelope
        url: "mailto:giuliano.colosimo@protonmail.com"

  page-footer:
    left: "© Copyright 2024 Giuliano Colosimo"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspiration for this site comes from [here](https://www.mm218.dev)."
    background: dark
    

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
